config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# CREATE (2 paths/actions)
# 1st render a form
get 'tasks/new', to: 'tasks#new', as: :new_task # new_task_path
# 2nd send the form&info/Params to the controller that will make it persistent
post 'tasks', to: 'tasks#create'


# READ
# verb path, to: controller#action(method)
get "tasks", to: "tasks#index" # tasks_path
get "tasks/:id", to: "tasks#show", as: :task


# UPDATE
# The first one to GET the pre-populated HTML form of existing record

get "tasks/:id/edit", to: "tasks#edit", as: :task_edit

# The second one to PATCH this form
patch "tasks/:id", to: "tasks#update"

# DELETE
delete "tasks/:id", to: "tasks#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
 #this is where we do validations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController


# READ
# 1. read all tasks (INDEX)
def index
  @tasks = Task.all
end

# 2. read a single task - based on id
def show
  @task = Task.find(params[:id])
end

# CREATE
# 1.create a new task object using form
def new
  @task =Task.new
end

# 2.Make task persistent (instance v) and redirect
def create
  @task = Task.new(task_params)
  @task.save
  redirect_to tasks_path
end

# UPDATE
# update a single task - based on id
# save into db
def edit
  @task = Task.find(params[:id])
end

def update
  @task = Task.find(params[:id])
  @task.update(task_params)
  redirect_to tasks_path
end

# DELETE
# delete a single task - based on id
def destroy
  @task = Task.find(params[:id])
  @task.destroy
  redirect_to tasks_path
end

private

def task_params
  params.require(:task).permit(:title, :details)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit a task</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>Your Task List</h1>
<h2>Tasks</h2>
  <% @tasks.each do |task|%>
  <h4><%= task.id %> - <%= link_to task.title, task_path(task) %></h4>
  <% end %>

<h4><%= link_to "Create a new task", new_task_path %></h4>

app/views/tasks/new.html.erb
<h1>Create new task</h1>


<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1>Task Detail</h1>
<h2><%= @task.title %></h2>
<p>Task details:<%= @task.details %></p>

<div class="completion">
  <% if @task.completed %>
  <i class="fas fa-check">Done</i>
  <% else %>
  <i class="far fa-square">Not Done</i>
  <% end %>
</div>

<div class="update">
<%= link_to "Edit Task", task_edit_path(@task) %>
</div>

<div class="delete">
  <%= link_to "Delete Task", task_path(@task),
      method: :delete,
      data: { confirm: "Are you sure?" } %>
</div>